
# Designed and developed by Patrick Leyshock (leyshock@ohsu.edu) And Jacob Bieker (jacob@bieker.us)

# Script consolidates multiple .xls files (generated by Aperio image-analysis software) into one .xlsx workbook
#   Input to script is multiple .xls files.  There is one .xls file per slide, with one or more rows, each row
#     corresponding to a region selected in the image
#   Output is a single .xlsx worksheet
#
# Assumptions:
#  1.  script is located in same directory as input files
#  2.   Perl is installed in the system
#  3.  input .xls files follow this naming convention:
#   (Initials-Of-Researcher)4.X M(Mouse Numer) (Mouse SID) (Stain).xls
#   E.g. "JB6.3 M3 22341 BrdU.xls""

#-------------------------------------------------------------------------
#-------------------------------------------------------------------------
#   Configuration
#-------------------------------------------------------------------------
#-------------------------------------------------------------------------
# Uncomment below if the JVM is running out of heap space
# Default should be fine for most data sets, tested on > 6000 files w/o 
# using this option
# options(java.parameters = "-Xmx1024m")

# Check if libraries are installed, if not, install them
if(require("XLConnect") & require("yaml") & require("gdata")){
  print("XLConnect, yaml are loaded correctly")
} else {
  print("trying to install XLConnect, yaml")
  install.packages("XLConnect")
  install.packages("yaml")
  install.packages("gdata")
  if(require("XLConnect") & require("yaml")){
    print("XLConnect, yaml are installed and loaded")
  } else {
    stop("could not install XLConnect, yaml, gdata")
  }
}
 
#Set the Perl location so that gdata can read it
perl <- "C:/strawberry/perl/bin/perl.exe"

#loads column names from config file config.yml
predefined.column.headers <- yaml.load_file("config.yml");

#-------------------------------------------------------------------------
#-------------------------------------------------------------------------
#   Utility functions
#-------------------------------------------------------------------------
#-------------------------------------------------------------------------

#   utility functions for AG4.5 M1 223316 BrdU.xls
get.mouse.id <- function(file.name) {
  #   remove file extension
  file.name <- strsplit(file.name, "\\.")[[1]][2];
  #   extract mouse number
  mouse.id.full <- strsplit(file.name, " ")[[1]][2];
  mouse.id <- strsplit(mouse.id.full, "M")[[1]][2];
  print(mouse.id)
  return(mouse.id);
}   #   get.mouse.id()

get.slide.num <- function(file.name)   {
  #   remove file extension
  file.name <- strsplit(file.name, "\\.")[[1]][2];
  #   extract mouse number
  slide.num <- strsplit(file.name, " ")[[1]][4];
  print(slide.num)
  return(slide.num);    
}   #   get.slide.num()

get.sid.name <- function(file.name)   {
  #   remove file extension
  file.name <- strsplit(file.name, "\\.")[[1]][2];
  #   extract sid number
  sid.name <- strsplit(file.name, " ")[[1]][3];
  print(sid.name)
  return(sid.name);
}   #   get.sid.name()
#-------------------------------------------------------------------------
#-------------------------------------------------------------------------
#   Setup
#-------------------------------------------------------------------------
#-------------------------------------------------------------------------

#Remove older consolidated_files file
fn <- "consolidated_files.xlsx";
if(file.exists(fn))
  file.remove(fn);

#   identify all .xls files in the directory 
files <- list.files(getwd(), pattern = ".xls$");

# remove master file with groups from list of files vector
files <- setdiff(files, "master.xls");

#   load master workbook so that know which groups Mice are in
masterwkbk <- loadWorkbook("master.xlsx", create = FALSE)

#   create list to hold output data.frames
output <- list();
#   create vector for storing the different slid numbers so that diff sheets created
slide.names <- c();
#   create workbook to save the data to
workbook <- loadWorkbook("consolidated_files.xlsx", create = TRUE);
#   create vector to store the different mice id for use in the summary
mouse.ids <- c();

#-------------------------------------------------------------------------
#-------------------------------------------------------------------------
#  Get data from master file
#-------------------------------------------------------------------------
#-------------------------------------------------------------------------
#   read in file content
master.workbook <- loadWorkbook("master.xlsx")
master.content <- readWorksheet(master.workbook, sheet = 1)
# Get vector of genotypes in numerical order to apply later
master.genotype <- master.content$Group


#-------------------------------------------------------------------------
#-------------------------------------------------------------------------
#   Read workbook contents into R
#-------------------------------------------------------------------------
#-------------------------------------------------------------------------

#   for all files in the directory
for(i in 1:length(files))   {
  
  #   get current file name
  file.name <- files[i];
  
  #   read in file content
  file.content = read.xls(file.name, perl = perl)
  
  #   extract column headings, for output (and possibly QC), for the first file only
  if(i == 1)
    column.headings <- colnames(file.content);
  print(file.name)
  #   extract relevant metadata from file name
  mouse.idnum <- get.mouse.id(file.name);
  slide.number <- get.slide.num(file.name);
  sid.number <- get.sid.name(file.name);
  #Convert to numeric right after getting number
  mouse.idnum <- as.numeric(mouse.idnum)
  mouse.group <-  master.genotype[as.numeric(mouse.idnum)]
  #Adds sid number to slide.names if it does not already exist in the vector
  if(!slide.number %in% slide.names) {
    slide.names <- c(slide.names, slide.number);
    #  Create a sheet in the master workbook for each sid
    createSheet(workbook, name = slide.number);
  }
  
  #Adds sid number to slide.names if it does not already exist in the vector
  if(!mouse.idnum %in% mouse.ids) {
    mouse.ids <- c(mouse.ids, mouse.idnum);
  }
  
  #   prepend metadata to file content
  file.content <- cbind(mouse.group, sid.number,slide.number, mouse.idnum, file.content);
  
  #   append file content to output data.frame
  output <- rbind(output, file.content);
  
  
}   #   for i

#-------------------------------------------------------------------------
#-------------------------------------------------------------------------
#   Export results
#-------------------------------------------------------------------------
#-------------------------------------------------------------------------


#Assign the column names to the data.frame
colnames(output) <- predefined.column.headers;

#Subset output so that Stain Num are not converted and stay strings
#Then add back in to data.frame 
factor_to_numbers <- output
factor_to_numbers$'SID' <- NULL
factor_to_numbers$'Group' <- NULL
factor_to_numbers$'Stain' <- NULL

#   convert factors to numbers
#       Not elegant, but needed so that the first three columns are converted
#       to their numeric values and not factor level values
factor_to_numbers<- sapply(factor_to_numbers, function(x) if(is.factor(x)) {
  as.numeric(as.character(x));
} else {
  as.numeric(x);
})

factor_to_numbers <- data.frame(factor_to_numbers)
#Reassign sid back to the temp data.frame
factor_to_numbers$'SID' <- output$'SID'
factor_to_numbers$'Group' <- output$'Group'
factor_to_numbers$'Stain' <- output$'Stain'
#Output is then given the modified data.frame for use in the rest of the script
output <- factor_to_numbers
#Reorder so that Stain and Group are the first two columns, like it was originally
output <- output[c(length(output) - 1, length(output) - 2, length(output),  seq(1, length(output) - 3, by = 1))]

#Reassign column names lost in above step
colnames(output) <- predefined.column.headers;

#Convert to numeric
mouse.ids <- as.numeric(mouse.ids);

#Order the output by the Group
output <- output[with(output, order(Group)),]

#  get the current sheets in the master workbook, which is in the same order
#  as sid.number
currentSheets <- getSheets(workbook);

for(i in 1:length(currentSheets)) {
  # Selects the subset of the output that has the same sid number
  output.subset <- output[output[,3]==slide.names[i],]
  #Drops the Stain number from the data.frame before writing it
  output.subset[,3] <- NULL
  #Get rid of sid number on columns, since that is stored in sheet name
  writeWorksheet(workbook, output.subset, sheet = currentSheets[i], 1, 1, header = TRUE)
}

#saves and actually writes the data to an Excel file
saveWorkbook(workbook);


#-------------------------------------------------------------------------
#-------------------------------------------------------------------------
#   Summary of Data
#-------------------------------------------------------------------------
#-------------------------------------------------------------------------


#Create the sheet for the summary
createSheet(workbook, name = "summary");

#Write the data of the summary run in the top left corner
writeWorksheet(workbook, date(), sheet = "summary", header = FALSE);

#create summary data.frame to put all the summary info into
mouse.summary.output <- data.frame();

#subset data for each mouse and perform calulations on it
for(i in 1:length(mouse.ids)) {
  #vector to store the data before putting into summary output
  current.summary <- NULL;
  #Add the mouse ID to the current.summary
  current.summary <- c(current.summary, mouse.ids[i])
  for(j in 1:length(slide.names)) {
    #subset output for current mouse and sid numbers
    mouse.data.current <- subset(output, output[,4]==mouse.ids[i] & output[,3]==slide.names[j])
    #Perform the calculations
    #   Averaging to get the number of cells per mm per sid and mouse
    average.size <- mean(mouse.data.current[,26]);
    #   First 3+ 2+ and 1+ average
    average.cells321 <- mean(mouse.data.current[,17]+mouse.data.current[,18]+mouse.data.current[,19]);
    average.321cellpermm <- average.cells321/average.size;
    #   Then 3+ 2+ average
    average.cells32 <- mean(mouse.data.current[,17]+mouse.data.current[,18]);
    average.32cellpermm <- average.cells32/average.size;
    #   Last 3+ average
    average.cells3 <- mean(mouse.data.current[,17]);
    average.3cellpermm <- average.cells3/average.size;
    #Append average cell to current summary
    current.summary <- c(current.summary, average.321cellpermm, average.32cellpermm, average.3cellpermm);
  }
  #End of inside for loop
  #save the current.summary to overall summary
  mouse.summary.output <- rbind(mouse.summary.output, current.summary)
}

#-------------------------------------------------------------------------
#-------------------------------------------------------------------------
#   Formatting Excel Document
#-------------------------------------------------------------------------
#-------------------------------------------------------------------------

#  Create CellStyles to use later
average.header <- createCellStyle(workbook, name = "AvgHeader")

#Set foreground color for average.header
setFillPattern(average.header, XLC$FILL.SOLID_FOREGROUND)
setFillForegroundColor(average.header, XLC$COLOR.TURQUOISE)
#setBorder(average.header, side = "all", XLC$BORDER.MEDIUM, color = XLC$COLOR.BLACK)

#    Create header for above the sid numbers
#have reference to get correct number of columns
reference <- paste0("C3:", LETTERS[(3 * length(slide.names))+2], "3")
mergeCells(workbook, sheet = "summary", reference)
mergedCellsIndex <- seq(2, length(slide.names)+1, 1)

#Write to the worksheet
writeWorksheet(workbook, "Average Cells/mm Per Stain for (3+, 2+, 1+), (3+, 2+), and (3+)", sheet = "summary", 3, 3, header = FALSE)
#Set CellStyle to average.header
setCellStyle(workbook, sheet = "summary", row = 3, col = mergedCellsIndex+1, cellstyle = average.header)

#Create the columns for the data to go in
summary.col.names <- c();

for(i in 1:length(slide.names)) {
  sid.name <- paste0("Stain ", as.character(slide.names[i]));
  #put in the initial names
  if(i==1){
    summary.col.names <- c("Mouse ID", sid.name);
  } else {
    # Very hack-y method at the moment
    summary.col.names <- c(summary.col.names, "NA", "NA", sid.name);
  }
}

# Make sid names span 3 columns so that the different averages can be included below
#  Create CellStyles to use later
sid.header <- createCellStyle(workbook, name = "StainHeader")

#Create the columns for the data to go in
summary.slide.names <- c();
#Index to track where to put the next header
index <- 0

for(i in 1:length(slide.names)) {
  sid.name <- paste0("Stain ", as.character(slide.names[i]));
  #    Create header for above the sid numbers
  #have reference to get correct number of columns
  # TODO add support for if the sids go into the double letter range
  if (i == 1) {
    mergeCells(workbook, sheet = "summary", "C4:E4")
  } else {
  reference <- paste0(LETTERS[index+3],"4:", LETTERS[index+5], "4")
  mergeCells(workbook, sheet = "summary", reference)
}
  #Write to the worksheet
  writeWorksheet(workbook, sid.name, sheet = "summary", 6, 2, header = FALSE)
  #up index by three since each sid takes up three columns
  index <- index + 3
}

#Apply column names to the summary output
colnames(mouse.summary.output) <- summary.col.names

#Write to file, not include headers so that extra line can be included
writeWorksheet(workbook, mouse.summary.output, sheet = "summary", startRow = 6, startCol = 2, header = FALSE)

# Add groups to summary sheet, adding it to mouse.summary.output changed all numerics to characters
group.names <- c();
mice.ids <- mouse.summary.output$`Mouse ID`
for(i in 1:length(mice.ids)) {
  current.data <- subset(output, output[,4]==mice.ids[i])
  current.data.row <- head(current.data, 1)
  # Taken from: https://stackoverflow.com/questions/24447877/invalid-factor-level-na-generated-when-pasting-in-a-dataframe-in-r
  current.data.row[,c(1)] <- sapply(current.data.row[,c(1)],as.character) 
  #Adds name to the vector
  group.names <- c(group.names, current.data.row$Group)
}
#Converts to data.frame starting with data.frame resulted in NA errors
group.names <- as.data.frame(group.names)

#Add the proper header for the data.frame if wanted to use later
colnames(group.names) <- "Group"

#Write to worksheet, again not including the header
writeWorksheet(workbook, group.names, sheet = "summary", startRow = 6, header = FALSE)

#--------------------------------------------------------------------------
#
#     Add in headers for the (3+,2+,1+), etc. and "Mouse ID", etc.
#      Kind of a hack-y way, but not sure of how else to have a space between headers
#      and data for the (3+,2+,1+), etc. 
#
#---------------------------------------------------------------------------

# Get the headers from summary column names and make into a data.frame
#Dummy data so summary.col.names can be made the headers. Will be overwritten later
dummy.data <- c();
#Add 'Group' to the summary column data names
summary.col.names <- c("Group", summary.col.names)
#Add enough entries for every sumamry.col.names entry
for(i in 1:length(summary.col.names)) {
  dummy.data <- cbind(dummy.data, NA)
}
#Convert to data.frame and apply the column names to the datafram
dummy.data <- as.data.frame(dummy.data)
colnames(dummy.data) <- summary.col.names
#Write the data frame
writeWorksheet(workbook, dummy.data, sheet = "summary", startRow = 4)

# Now add the information below the different sids

#Empty places for the first two spots, for Groups and Mouse ID
aperio.labels <- c(NA, NA)
#Now add the three labels for each sid
for( i in 1:length(slide.names)) {
  aperio.labels <- cbind(aperio.labels, "(3+, 2+, 1+)", "(3+, 2+)", "(3+)")
}
#Convert to data.frame to XLConnect can write it 
aperio.labels <- as.data.frame(aperio.labels, stringsAsFactors=FALSE)

#Only choose the first line, as other wise there is a row for each NA
aperio.labels <- head(aperio.labels, 1)
#Write to file
writeWorksheet(workbook, aperio.labels, sheet = "summary", startRow = 5, startCol = 2, header = FALSE)

#Save to workbook after creating the summary
saveWorkbook(workbook)