#!/usr/bin/env bash

if [[ ! -e ${LKTOOLS_DIR}/oncotator || ! -z $FORCE_REINSTALL ]];
then
    echo "Cleaning up previous installs"
    rm -Rf oncotator*
    rm -Rf $LKTOOLS_DIR/oncotator

    wget --read-timeout=10 https://github.com/broadinstitute/oncotator/archive/v1.8.0.0.tar.gz
    tar zxvf oncotator-1.8.0.0.tar.gz

    wget --read-timeout=10 http://www.broadinstitute.org/~lichtens/oncobeta/oncotator_v1_ds_Jan262015.tar.gz
    tar zxvf oncotator_v1_ds_Jan262015.tar.gz

    cd oncotator-1.8.0.0

    pip install virtualenv
    ./scripts/create_oncotator_venv.sh -e $LKTOOLS_DIR/oncotator

    source $LKTOOLS_DIR/oncotator/bin/activate
    python setup.py install
    deactivate
else
    echo "Already installed"
fi